musicas = [
    "Bruno Mars - When I Was Your Man",
    "Bruno Mars - Just The Way You ",
    "Bruno Mars - Count On Me",
    "Bruno Mars - Talking To The Moon",
    "Bruno Mars - Locked Out Of Heaven",
    "Bruno Mars - It Will Rain",
    "Bruno Mars - The Lazy Song",
    "Bruno Mars - That's What I Like",
    "Bruno Mars - Marry You",
    "Bruno Mars - Grenade",
    "Bruno Mars - Uptown Funk (feat. Mark Ronson)",
    "Bruno Mars - Nothin' On You (feat. B.o.B.)",
    "Bruno Mars - Leave The Door Open (feat. Anderson .Paak)",
    "Bruno Mars - 24K Magic",
    "Bruno Mars - Treasure",
    "Bruno Mars - Billionaire (feat. Travie McCoy)",
    "Bruno Mars - Versace On The Floor",
    "Bruno Mars - Nothin' On You (Live)",
    "Bruno Mars - Gorilla",
    "Bruno Mars - Finesse (remix) (feat. Cardi B)",
    "Bruno Mars - Wake Up In The Sky (feat. Gucci Mane & Kodak Black)",
    "Bruno Mars - Love's Train (feat. Anderson. Paak)",
    "Bruno Mars - Don't Give Up",
    "Bruno Mars - Runaway Baby",
    "Bruno Mars - Young Girls",
    "Bruno Mars - Too Good To Say Goodbye",
    "Bruno Mars - Smokin' Out The Window (feat. Anderson .Paak)",
    "Bruno Mars - Finesse",
    "Bruno Mars - If I Knew",
    "Bruno Mars - Chunky",
    "Bruno Mars - Skate (feat. Anderson .Paak)",
    "Bruno Mars - Lighters (feat. Eminem & Royce da 5'9)",
    "Bruno Mars - After Last Night (feat. Andersoon .Paak, Bootsy Collins & Thundercat)",
    "Bruno Mars - Liquor Store Blues (feat. Damian Marley)",
    "Bruno Mars - Rest Of My Life",
    "Bruno Mars - Our First Time",
    "Bruno Mars - Fly as Me (feat. Anderson .Paak)",
    "Bruno Mars - Moonshine",
    "Bruno Mars - Natalie",
    "Bruno Mars - Perm",
    "Bruno Mars - Blast Off (feat. Anderson .Paak)",
    "Bruno Mars - Calling All My Lovelies",
    "Bruno Mars - Mirror (feat. Lil' Wayne)",
    "Bruno Mars - Voices In My Head",
    "Bruno Mars - Please Me (feat. Cardi B)",
    "Bruno Mars - Put On a Smile (feat. Anderson .Paak)",
    "Bruno Mars - 777 (feat. Anderson .Paak)",
    "Bruno Mars - Show Me",
    "Bruno Mars - Again",
    "Bruno Mars - Straight Up & Down",
    "Bruno Mars - Love (feat. Jaeson Ma)",
    "Bruno Mars - Grenade (remix feat. Lil Wayne)",
    "Bruno Mars - All About You",
    "Bruno Mars - Who Is",
    "Bruno Mars - Money Make Her Smile",
    "Bruno Mars - All I Ask",
    "Bruno Mars - Just The Way You Are (feat. Lupe Fiasco)",
    "Bruno Mars - Somewhere In Brooklyn",
    "Bruno Mars - The Other Side",
    "Bruno Mars - All She Knows",
    "Bruno Mars - Today My Life Begins",
    "Bruno Mars - BLOW (feat. Ed Sheeran & Chris Stapleton)",
    "Bruno Mars - All I Need",
    "Bruno Mars - Under The Sea",
    "Bruno Mars - 3D (feat. Far East Movement)",
    "Bruno Mars - A Stranger",
    "Bruno Mars - Step By Step",
    "Bruno Mars - That's What I Like (Gucci Mane Remix)",
    "Bruno Mars - That's What I Like (PARTYNEXTDOOR Remix)",
    "Bruno Mars - This Is My Love (feat. Gold 1 & Jaeson Ma)",
    "Bruno Mars - Young, Live and Free (feat. Snoop Dogg & Wiz Khalifa)",
    "Bruno Mars - Long Distance",
    "Bruno Mars - Can't Come Back To Me (feat. Layzie Bone)",
    "Bruno Mars - Dance In The Mirror",
    "Bruno Mars - Just The Way You Are / Locked Out Of Heaven (Medley)",
    "Bruno Mars - Before It Explode",
    "Bruno Mars - If I Catch You",
    "Bruno Mars - Never Say U Can't",
    "Bruno Mars - Old & Crazy",
    "Bruno Mars - There I Go Again",
    "Bruno Mars - Where Did She Go",
    "Bruno Mars - Faded",
    "Bruno Mars - Gorilla G-Mix (feat. R. Kelly & Pharrell)",
    "Bruno Mars - I Love You More Today Than Yesterday",
    "Bruno Mars - I Was Only Dancing",
    "Bruno Mars - I'm Not The One",
    "Bruno Mars - Like Tonight",
    "Bruno Mars - Move On",
    "Bruno Mars - Only When You're Lonely",
    "Bruno Mars - She Got Me",
    "Bruno Mars - Tonight (feat. Johnny Angel)",
    "Bruno Mars - Valerie",
    "Bruno Mars - Dream Taker",
    "Bruno Mars - Finesse (Megamix) (feat. Cardi B, Nicki Minaj, Queen Latifah, Foxy Brown, Missy Elliott, Left-Eye, Lil' Kim & Lauryn Hill)",
    "Bruno Mars - Getchu On The Run",
    "Bruno Mars - Her World Goes On (Feat. David Guetta)",
    "Bruno Mars - Killa On Tha Run",
    "Bruno Mars - Press It (Feat. Philip Lawrence)",
    "Bruno Mars - Super Bowl Medley (feat. Red Hot Chili Peppers)",
    "Bruno Mars - Top Of The World",
    "Bruno Mars - Turn Around",
    "Bruno Mars - Wait For You (feat. Claude Kelly)",
    "Bruno Mars - Welcome Back",
    "Bruno Mars - Catch A Grenade (remix The Hooligans)",
    "Bruno Mars - Circles",
    "Bruno Mars - Gold (feat. The Dream)",
    "Bruno Mars - Ladies Is Pimps To",
    "Bruno Mars - Like Tonight (feat. Jackie Boyz )",
    "Bruno Mars - Lost",
    "Bruno Mars - Mama's Worst Nightmare",
    "Bruno Mars - Part Of Your World",
    "Bruno Mars - Rocketeer (feat Far East Movement)",
    "Bruno Mars - Starting Today",
    "Bruno Mars - Take The Long Way Home",
    "Bruno Mars - Watching Her Move",
    "Bruno Mars - We Are Fighters",
    "Bruno Mars - We'll Be Alright",
    "Bruno Mars - Click Clack",
    "Bruno Mars - I Gotta Hate Her",
    "Bruno Mars - Never Close Our Eyes (feat. Adam Lambert)",
    "Bruno Mars - Silent Night",
    "Bruno Mars - Trippin' Out",
    "Bruno Mars - Turn Me On (feat. H20)",
    "Bruno Mars - Freedom (feat. Jackie Boyz)",
    "Bruno Mars - Girl In The Window",
    "Bruno Mars - Innocent",
    "Bruno Mars - On Fire",
    "Bruno Mars - Phantom Planet",
    "Bruno Mars - Sugarhoneycocoa (feat. Big Gipp)",
    "Bruno Mars - The First Time (feat. David Guetta)",
]

function Indicar_musica() {
    musica = musicas[Math.floor(Math.random() * musicas.length)];
    document.getElementById("Texto_8").textContent = musica;

}
